import "./globals.css"
import { Inter, Domine } from "next/font/google"
import { ThemeProvider } from "@/components/themes/theme-provider"
import { NavbarDesktop } from "@/components/navbar/navbar-desktop"
import type { Metadata } from "next"

const inter = Inter({
  variable: "--font-inter",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
  subsets: ["latin"],
})

const domine = Domine({
  variable: "--font-domine",
  weight: ["400", "500", "600", "700"],
  display: "swap",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${domine.variable}`}>
      <body className="min-h-screen bg-background font-inter antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavbarDesktop />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
